name: Docker Build and Push

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1 * *'  # At midnight on the 1st day of each month

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up date for tagging
        id: date_tag
        run: echo "DATE_TAG=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Build and push Docker image with timestamp
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          push: true
          tags: |
            kartaltabak/docker-connect-avro-library:${{ env.DATE_TAG }}
            kartaltabak/docker-connect-avro-library:latest
